### ISSUE TITLE
Please add this patch

### ISSUE THREAD

**Issue by shpinog** [yurikoles-aur/linux-drm-next-git#2]
Could you add this patch
https://lists.freedesktop.org/archives/amd-gfx/2019-September/039982.html

Details:
https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-LRU-Bulk-Moves-Valve
https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Re-Enable-Bulk-Moves

**Comment by ranolfi** [comment]
@shpinog can you check [this](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Bulk-Moves-5.4-Fix) to clarify whether patching is still necessary?
